<a href="https://colab.research.google.com/github/TAM-DS/TAM-DS/blob/main/Similarity_Analysis_Ideal_Customer_Profile_1567.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Ideal Customer Profile**
Client #1567 (SME Bank ICP_Data) requested a profile for the ideal target customer for their new product and service.
This project will include a range of demographic, psychographic and
behavioral factors (age, gender, income, education, location, interests, values and purchase history) + other relevent attributes (job title, industry, company size.)

Table of Contents:
Seed Creation
Seed Propogation
Similarity Analysis with Euclidean Distance

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
Icp_data=pd.read_csv('/content/drive/MyDrive/Ideal+Customer+Profile+-+Bank+Personal+Loan+Modelling.csv')
Icp_data

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,29,3,40,92697,1,1.9,3,0,0,0,0,1,0
4996,4997,30,4,15,92037,4,0.4,1,85,0,0,0,1,0
4997,4998,63,39,24,93023,2,0.3,3,0,0,0,0,0,0
4998,4999,65,40,49,90034,3,0.5,2,0,0,0,0,1,0
4999,5000,28,4,83,92612,3,0.8,1,0,0,0,0,1,1

In [ ]:
Icp_data.columns

Index(['ID', 'Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'CCAvg',
       'Education', 'Mortgage', 'Personal Loan', 'Securities Account',
       'CD Account', 'Online', 'CreditCard'],
      dtype='object')

In [ ]:
Icp_data.describe()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000
mean,2500.500000,45.338400,20.104600,73.774200,93152.503000,2.396400,1.937938,1.881000,56.498800,0.096000,0.104400,0.06040,0.596800,0.294000
std,1443.520003,11.463166,11.467954,46.033729,2121.852197,1.147663,1.747659,0.839869,101.713802,0.294621,0.305809,0.23825,0.490589,0.455637
min,1.000000,23.000000,-3.000000,8.000000,9307.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,1250.750000,35.000000,10.000000,39.000000,91911.000000,1.000000,0.700000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,2500.500000,45.000000,20.000000,64.000000,93437.000000,2.000000,1.500000,2.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000
75%,3750.250000,55.000000,30.000000,98.000000,94608.000000,3.000000,2.500000,3.000000,101.000000,0.000000,0.000000,0.00000,1.000000,1.000000
max,5000.000000,67.000000,43.000000,224.000000,96651.000000,4.000000,10.000000,3.000000,635.000000,1.000000,1.000000,1.00000,1.000000,1.000000

In [ ]:
#Declare which variables are strategic:
Feature_variables = ['Age','Experience','Income','Family','CCAvg','Education','Mortgage','Securities Account']
Target_varaible = ['Personal Loan']

In [ ]:
#Import Packages
from sklearn.preprocessing import StandardScaler #Mean of 0 |STD of 1
data_to_scale = Icp_data[Feature_variables]
#Create a scaler object
scaler = StandardScaler()
#Fit and transform the selected columns using the scaler object
scaled_data = scaler.fit_transform(data_to_scale)
#Convert the scaled data back to a DataFrame
scaled_df = pd.DataFrame(scaled_data, columns=Feature_variables)
#Combine the scaled columns with the 'personal loan' column
scaled_df['Personal Loan'] = Icp_data['Personal Loan']
scaled_df['ID'] = Icp_data['ID']

In [ ]:
scaled_df.head(10)

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Securities Account,Personal Loan,ID
0,-1.774417,-1.666078,-0.538229,1.397414,-0.193385,-1.049078,-0.555524,2.928915,0,1
1,-0.029524,-0.096330,-0.864109,0.525991,-0.250611,-1.049078,-0.555524,2.928915,0,2
2,-0.552992,-0.445163,-1.363793,-1.216855,-0.536736,-1.049078,-0.555524,-0.341423,0,3
3,-0.901970,-0.968413,0.569765,-1.216855,0.436091,0.141703,-0.555524,-0.341423,0,4
4,-0.901970,-1.055621,-0.625130,1.397414,-0.536736,0.141703,-0.555524,-0.341423,0,5
5,-0.727481,-0.619580,-0.972736,1.397414,-0.880087,0.141703,0.968512,-0.341423,0,6
6,0.668434,0.601336,-0.038545,-0.345432,-0.250611,0.141703,-0.555524,-0.341423,0,7
7,0.406700,0.339711,-1.124814,-1.216855,-0.937312,1.332484,-0.555524,-0.341423,0,8
8,-0.901970,-0.881204,0.156983,0.525991,-0.765637,0.141703,0.467055,-0.341423,0,9
9,-0.989215,-0.968413,2.307795,-1.216855,3.984049,1.332484,-0.555524,-0.341423,1,10

In [ ]:
#Seed Identification
Seed_data = scaled_df[scaled_df['Personal Loan'] == 1].reset_index(drop=True)
Prospect_data = scaled_df[scaled_df['Personal Loan'] == 0].reset_index(drop=True)
Seed_data.reset_index()

,index,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Securities Account,Personal Loan,ID
0,0,-0.989215,-0.968413,2.307795,-1.216855,3.984049,1.332484,-0.555524,-0.341423,1,10
1,1,-0.640236,-0.532371,1.221527,1.397414,1.580593,1.332484,0.762030,-0.341423,1,17
2,2,0.057721,0.078086,2.590225,-0.345432,3.526248,1.332484,-0.555524,-0.341423,1,19
3,3,-0.640236,-0.619580,0.982547,-1.216855,0.779442,0.141703,-0.555524,-0.341423,1,30
4,4,-0.291258,-0.183538,1.460506,0.525991,1.752269,1.332484,-0.555524,2.928915,1,39
...,...,...,...,...,...,...,...,...,...,...,...
475,475,-0.640236,-0.619580,1.199801,0.525991,1.237243,1.332484,-0.555524,-0.341423,1,4884
476,476,-0.204013,-0.096330,1.025998,-1.216855,-0.708412,0.141703,-0.555524,-0.341423,1,4928
477,477,-1.512683,-1.404454,0.830470,-0.345432,-0.193385,0.141703,-0.555524,-0.341423,1,4942
478,478,0.057721,-0.009122,1.047724,0.525991,0.607766,1.332484,-0.555524,-0.341423,1,4963
479,479,-1.425438,-1.317246,1.330153,0.525991,1.923944,-1.049078,-0.555524,-0.341423,1,4981

In [ ]:
Prospect_data
#Potential customers to convert

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Securities Account,Personal Loan,ID
0,-1.774417,-1.666078,-0.538229,1.397414,-0.193385,-1.049078,-0.555524,2.928915,0,1
1,-0.029524,-0.096330,-0.864109,0.525991,-0.250611,-1.049078,-0.555524,2.928915,0,2
2,-0.552992,-0.445163,-1.363793,-1.216855,-0.536736,-1.049078,-0.555524,-0.341423,0,3
3,-0.901970,-0.968413,0.569765,-1.216855,0.436091,0.141703,-0.555524,-0.341423,0,4
4,-0.901970,-1.055621,-0.625130,1.397414,-0.536736,0.141703,-0.555524,-0.341423,0,5
...,...,...,...,...,...,...,...,...,...,...
4515,-1.425438,-1.491662,-0.733757,-1.216855,-0.021710,1.332484,-0.555524,-0.341423,0,4996
4516,-1.338194,-1.404454,-1.276892,1.397414,-0.880087,-1.049078,0.280238,-0.341423,0,4997
4517,1.540880,1.647835,-1.081363,-0.345432,-0.937312,1.332484,-0.555524,-0.341423,0,4998
4518,1.715370,1.735043,-0.538229,0.525991,-0.822862,0.141703,-0.555524,-0.341423,0,4999
4519,-1.512683,-1.404454,0.200434,0.525991,-0.651186,-1.049078,-0.555524,-0.341423,0,5000

In [ ]:
seed=Seed_data[:1]
seed

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Securities Account,Personal Loan,ID
0,-0.989215,-0.968413,2.307795,-1.216855,3.984049,1.332484,-0.555524,-0.341423,1,10

In [ ]:
Icp_data[Icp_data['ID']==10]

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
9,10,34,9,180,93023,1,8.9,3,0,1,0,0,0,0

In [ ]:
#Euclidean Distance is the square root of the sum of squared diffrences
#between the coresponding features of the two points.

from scipy.spatial.distance import euclidean
distance_metric=[]
for i in range(len(Prospect_data)):
      distance = euclidean(Prospect_data.loc[i,Feature_variables].values,
                           seed.loc[0,Feature_variables].values)
      distance_metric.append(distance)

In [ ]:
Prospect_data['distance'] = distance_metric

In [ ]:
#Top 30 prospects for outreach

Prospect_data.sort_values('distance')[0:30]

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Securities Account,Personal Loan,ID,distance
2648,-1.076460,-1.055621,2.351246,-1.216855,3.812373,-1.049078,-0.555524,-0.341423,0,2953,2.391320
557,-0.727481,-0.706788,2.307795,-1.216855,3.812373,-1.049078,-0.555524,-0.341423,0,615,2.416249
4150,-0.727481,-0.706788,2.286070,-1.216855,3.812373,-1.049078,-0.555524,-0.341423,0,4604,2.416347
4460,-1.076460,-1.055621,1.916739,-1.216855,3.812373,-1.049078,-0.555524,-0.341423,0,4938,2.422695
3745,-0.727481,-0.706788,2.590225,-1.216855,3.812373,-1.049078,-0.555524,-0.341423,0,4157,2.432700
1612,-0.901970,-0.881204,1.503956,-1.216855,3.812373,-1.049078,-0.555524,-0.341423,0,1798,2.522436
491,-0.901970,-0.881204,1.960189,-0.345432,3.354572,-1.049078,-0.555524,-0.341423,0,545,2.638845
3427,-0.814726,-0.793996,1.960189,-0.345432,3.354572,-1.049078,-0.555524,-0.341423,0,3808,2.647480
157,-0.640236,-0.619580,2.112267,-0.345432,3.354572,-1.049078,-0.555524,-0.341423,0,173,2.666300
3081,-0.552992,-0.445163,2.199168,-0.345432,3.469022,-1.049078,-0.555524,-0.341423,0,3428,2.678124
582,-0.901970,-0.881204,1.417055,-0.345432,3.354572,-1.049078,-0.555524,-0.341423,0,642,2.763348
1094,-0.378502,-0.270747,1.981915,-0.345432,3.469022,-1.049078,-0.555524,-0.341423,0,1221,2.768099
444,-0.378502,-0.270747,1.873288,-0.345432,3.469022,-1.049078,-0.555524,-0.341423,0,495,2.782979
1970,-0.291258,-0.183538,2.112267,-0.345432,3.469022,-1.049078,-0.555524,-0.341423,0,2192,2.799619
2859,-0.552992,-0.445163,1.460506,-0.345432,3.469022,-1.049078,-0.555524,-0.341423,0,3185,2.806857
3195,-0.378502,-0.357955,1.764661,-1.216855,2.896771,-1.049078,-0.555524,-0.341423,0,3554,2.809739
2629,-0.378502,-0.357955,1.742936,-1.216855,2.896771,-1.049078,-0.555524,-0.341423,0,2933,2.814019
3805,-0.204013,-0.183538,2.829204,-0.345432,3.926823,-1.049078,-0.555524,-0.341423,0,4226,2.817610
2069,-1.163704,-1.142829,2.416422,-0.345432,2.725096,-1.049078,-0.555524,-0.341423,0,2306,2.844089
2067,-0.291258,-0.270747,1.764661,-1.216855,2.896771,-1.049078,-0.555524,-0.341423,0,2303,2.850068
3610,-0.291258,-0.183538,2.503324,-0.345432,3.240122,-1.049078,-0.555524,-0.341423,0,4010,2.850622
1460,-1.250949,-1.230037,2.307795,-0.345432,2.725096,-1.049078,-0.555524,-0.341423,0,1627,2.855368
2194,-0.116768,-0.096330,2.764028,-0.345432,3.926823,-1.049078,-0.555524,-0.341423,0,2448,2.857329
2625,-1.250949,-1.230037,2.199168,-0.345432,2.725096,-1.049078,-0.555524,-0.341423,0,2929,2.857434
3656,-1.250949,-1.230037,2.177443,-0.345432,2.725096,-1.049078,-0.555524,-0.341423,0,4061,2.858342
2223,-1.338194,-1.317246,2.264345,-0.345432,2.725096,-1.049078,-0.555524,-0.341423,0,2479,2.874289
800,-0.116768,-0.096330,1.742936,-0.345432,3.926823,-1.049078,-0.555524,-0.341423,0,882,2.876673
47,-0.378502,-0.270747,1.417055,-0.345432,3.469022,-1.049078,-0.555524,-0.341423,0,56,2.889566
295,-1.512683,-1.404454,2.546774,-1.216855,2.513363,-1.049078,-0.555524,-0.341423,0,330,2.890677
2563,-0.814726,-0.793996,1.829837,-0.345432,3.354572,-1.049078,0.565380,-0.341423,0,2859,2.893647

In [ ]:
#Final List of The Clients Top Targets

target_customers = Prospect_data.sort_values('distance')[0:30]

In [ ]:
target_customers = Icp_data[Icp_data['ID'].isin(target_customers['ID'])]
target_customers

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
55,56,41,17,139,94022,2,8.00,1,0,0,0,0,1,0
172,173,38,13,171,92717,2,7.80,1,0,0,0,0,1,0
329,330,28,4,191,90064,1,6.33,1,0,0,0,0,1,0
494,495,41,17,160,92647,2,8.00,1,0,0,0,0,1,0
544,545,35,10,164,91614,2,7.80,1,0,0,0,0,1,0
614,615,37,12,180,90034,1,8.60,1,0,0,0,0,1,1
641,642,35,10,139,95060,2,7.80,1,0,0,0,0,0,0
881,882,44,19,154,92116,2,8.80,1,0,0,0,0,1,0
1220,1221,41,17,165,94143,2,8.00,1,0,0,0,0,1,0
1626,1627,31,6,180,93108,2,6.70,1,0,0,0,0,0,0
1797,1798,35,10,143,91365,1,8.60,1,0,0,0,0,1,1
2191,2192,42,18,171,90027,2,8.00,1,0,0,0,0,1,0
2302,2303,42,17,155,92806,1,7.00,1,0,0,0,0,0,1
2305,2306,32,7,185,92009,2,6.70,1,0,0,0,1,1,1
2447,2448,44,19,201,95819,2,8.80,1,0,0,0,0,1,1
2478,2479,30,5,178,94063,2,6.70,1,0,0,0,0,0,0
2858,2859,36,11,158,95054,2,7.80,1,114,0,0,0,1,1
2928,2929,31,6,175,95005,2,6.70,1,0,0,0,0,1,0
2932,2933,41,16,154,92407,1,7.00,1,0,0,0,0,0,1
2952,2953,33,8,182,94065,1,8.60,1,0,0,0,0,0,0
3184,3185,39,15,141,92354,2,8.00,1,0,0,0,0,1,0
3427,3428,39,15,175,94080,2,8.00,1,0,0,0,0,1,0
3553,3554,41,16,155,95070,1,7.00,1,0,0,0,0,0,0
3807,3808,36,11,164,95051,2,7.80,1,0,0,0,0,1,1
4009,4010,42,18,189,91605,2,7.60,1,0,0,0,0,1,0
4060,4061,31,6,174,93023,2,6.70,1,0,0,0,0,1,1
4156,4157,37,12,193,92780,1,8.60,1,0,0,0,0,0,0
4225,4226,43,18,204,91902,2,8.80,1,0,0,0,0,1,0
4603,4604,37,12,179,91768,1,8.60,1,0,0,0,0,1,0
4937,4938,33,8,162,94960,1,8.60,1,0,0,0,1,1,1

After Meeting with Marketing team, it was detrmined that we create a more ROBUST Manual Seed Creation with an ID of 5004

In [ ]:
new_seed = {'Age':45, 'Experience':8, 'Income':250, 'Family':0, 'CCAvg':10, 'Education':3, 'Mortgage':0, 'Personal Loan':1, 'Securities Account':0, 'ID':5004}
new_seed_df = pd.DataFrame([new_seed])

In [ ]:
distance_metric_new_seed=[]
for i in range(len(Prospect_data)):
      distance = euclidean(Prospect_data.loc[i,Feature_variables].values,
                           new_seed_df.loc[0,Feature_variables].values)
      distance_metric.append(distance)

In [ ]:
distance_metric[:5]

[253.66579379321755,
 253.68494897275528,
 254.26052816383987,
 252.3615858038854,
 253.58525641914304]